src/Pangea.Coding.Challenge/Models/GitHubOwner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pangea.Coding.Challenge.Models
{
    public class GitHubOwner
    {
        public int GitHubOwnerId { get; set; }
        public int id { get; set; }
        public string login { get; set; }
        public string avatar_url { get; set; }
        public string gravatar_id { get; set; }
        public string url { get; set; }
        public string html_url { get; set; }
        public string followers_url { get; set; }
        public string following_url { get; set; }
        public string gists_url { get; set; }
        public string starred_url { get; set; }
        public string subscriptions_url { get; set; }
        public string organizations_url { get; set; }
        public string repos_url { get; set; }
        public string events_url { get; set; }
        public string received_events_url { get; set; }
        public string type { get; set; }
        public bool site_admin { get; set; }
    }
}

src/Pangea.Coding.Challenge/Models/GitHubPermissions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pangea.Coding.Challenge.Models
{
    public class GitHubPermissions
    {
        public int GitHubPermissionsId { get; set; }
        public bool admin { get; set; }
        public bool push { get; set; }
        public bool pull { get; set; }
    }
}

src/Pangea.Coding.Challenge/Models/GitHubRepository.cs
namespace Pangea.Coding.Challenge.Models
{
    public class GitHubRepository
    {
        public int GitHubRepositoryId { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string full_name { get; set; }
        public string html_url { get; set; }
        public string description { get; set; }
        public bool fork { get; set; }
        public string url { get; set; }
        public string forks_url { get; set; }
        public string keys_url { get; set; }
        public string collaborators_url { get; set; }
        public string teams_url { get; set; }
        public string hooks_url { get; set; }
        public string issue_events_url { get; set; }
        public string events_url { get; set; }
        public string assignees_url { get; set; }
        public string branches_url { get; set; }
        public string tags_url { get; set; }
        public string blobs_url { get; set; }
        public string git_tags_url { get; set; }
        public string git_refs_url { get; set; }
        public string trees_url { get; set; }
        public string statuses_url { get; set; }
        public string languages_url { get; set; }
        public string stargazers_url { get; set; }
        public string contributors_url { get; set; }
        public string subscribers_url { get; set; }
        public string subscription_url { get; set; }
        public string commits_url { get; set; }
        public string git_commits_url { get; set; }
        public string comments_url { get; set; }
        public string issue_comment_url { get; set; }
        public string contents_url { get; set; }
        public string compare_url { get; set; }
        public string merges_url { get; set; }
        public string archive_url { get; set; }
        public string downloads_url { get; set; }
        public string issues_url { get; set; }
        public string pulls_url { get; set; }
        public string milestones_url { get; set; }
        public string notifications_url { get; set; }
        public string labels_url { get; set; }
        public string releases_url { get; set; }
        public string deployments_url { get; set; }
        public string created_at { get; set; }
        public string updated_at { get; set; }
        public string pushed_at { get; set; }
        public string git_url { get; set; }
        public string ssh_url { get; set; }
        public string clone_url { get; set; }
        public string svn_url { get; set; }
        public string homepage { get; set; }
        public int size { get; set; }
        public int stargazers_count { get; set; }
        public int watchers_count { get; set; }
        public string language { get; set; }
        public bool has_issues { get; set; }
        public bool has_downloads { get; set; }
        public bool has_wiki { get; set; }
        public bool has_pages { get; set; }
        public int forks_count { get; set; }
        public string mirror_url { get; set; }
        public int open_issues_count { get; set; }
        public int forks { get; set; }
        public int open_issues { get; set; }
        public int watchers { get; set; }
        public string default_branch { get; set; }
        public GitHubOwner owner { get; set; }
        public GitHubPermissions permissions { get; set; }
    }
}

src/Pangea.Coding.Challenge/Models/Model.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace Pangea.Coding.Challenge.Models
{
    public class PangeaContext : DbContext
    {
        public PangeaContext(DbContextOptions<PangeaContext> options)
            : base(options)
        { }

        public DbSet<GitHubRepository> Repositories { get; set; }
    }
}

src/Pangea.Coding.Challenge/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pangea.Coding.Challenge.Models;
using Microsoft.EntityFrameworkCore;

namespace Pangea.Coding.Challenge.Controllers
{
    public class HomeController : Controller
    {
        private readonly PangeaContext _context;

        public HomeController(PangeaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<GitHubRepository> repositories =
                _context.Repositories
                    .Include(e => e.owner)
                    .ToList();

            ViewData["Repositories"] = repositories;

            return View();
        }
    }
}

src/Pangea.Coding.Challenge/Controllers/LoadDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pangea.Coding.Challenge.Models;
using Pangea.Coding.Challenge.Libraries;

namespace Pangea.Coding.Challenge.Controllers
{
    public class LoadDataController : Controller
    {
        private readonly PangeaContext _context;
        private readonly IGithubClient _githubClient;

        public LoadDataController(PangeaContext context, IGithubClient githubClient)
        {
            _context = context;
            _githubClient = githubClient;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            if (_context.Repositories.ToList().Count == 0)
            {
                // populate the data from the GitHub API
                foreach(GitHubRepository repo in await _githubClient.FetchRepositories("orgs/gopangea/repos"))
                {
                    _context.Repositories.Add(repo);
                }

                _context.SaveChanges();
            }

            return RedirectToAction("Index", "Home", new { });
        }
    }
}

src/Pangea.Coding.Challenge/Controllers/PurgeDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pangea.Coding.Challenge.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Pangea.Coding.Challenge.Controllers
{
    public class PurgeDataController : Controller
    {
        private readonly PangeaContext _context;

        public PurgeDataController(PangeaContext context)
        {
            _context = context;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            foreach(GitHubRepository repo in _context.Repositories.ToList())
            {
                _context.Remove(repo);
            }

            _context.SaveChanges();

            return RedirectToAction("Index", "Home", new { });
        }
    }
}

src/Pangea.Coding.Challenge/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/Pangea.Coding.Challenge/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Pangea.Coding.Challenge/Views/Home/Index.cshtml
@model IEnumerable<Pangea.Coding.Challenge.Models.GitHubRepository>

@{
    ViewData["Title"] = "Pangea Assignement";
}

<div class="row page-header">
    <div class="col-lg-12">
        <table class="table table-bordered table-bordered table-striped table-hover table-responsive">
            <thead>
                <tr>
                    <th>Repo Name</th>
                    <th>Language</th>
                    <th>Avatar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var repo in ViewData["Repositories"] as List<Pangea.Coding.Challenge.Models.GitHubRepository>)
                {
                <tr>
                    <td>
                        <a href="@repo.html_url">@repo.name</a>
                    </td>
                    <td>
                        @repo.language
                    </td>
                    <td>
                        <img width="75" height="75" src="@repo.owner.avatar_url" />
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/Pangea.Coding.Challenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pengea.Coding.Challenge</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Pangea Assignement</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="LoadData" asp-action="Index">Load Data</a></li>
                    <li><a asp-area="" asp-controller="PurgeData" asp-action="Index">Purge Data</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Pangea.Coding.Challenge</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>